
# ======================= INSTALL_DIR ========================= #
# Provide the install directory here:
#INSTALL_PATH=${HOME}/Applications/GNU/spring
#INSTALL_PATH=${HOME}/Applications/Intel/springO3

# ======================= INSTALL_DIR ========================= #

# ========================= Vendor ============================ #
# Provide the vendor of the compiler here:
# For ifort VENDOR=intel, for gfortran VENDOR=gnu

DEBUG=0

VENDOR=gnu
#LINEARALG=openblas
LINEARALG=blas_lapack

#VENDOR=intel

#CO_CONF_FILE_CREATEDM2=${HOME}/intelCoConfig/ConfigDM2.txt
#CO_CONF_FILE_CREATEDM3=${HOME}/intelCoConfig/ConfigDM3.txt
#CO_CONF_FILE_CREATEDM4=${HOME}/intelCoConfig/ConfigDM4.txt
#CO_CONF_FILE_RECONST2=${HOME}/intelCoConfig/ConfigRCNST2.txt
#CO_CONF_FILE_RECONST3=${HOME}/intelCoConfig/ConfigRCNST3.txt
#CO_CONF_FILE_RECONST4=${HOME}/intelCoConfig/ConfigRCNST4.txt
#CO_CONF_FILE_FREE_ENG=${HOME}/intelCoConfig/ConfigFREE.txt
#CO_CONF_FILE_LINEWIDTH=${HOME}/intelCoConfig/Linewidth.txt
#CO_CONF_FILE_KAPPA_ITER=${HOME}/intelCoConfig/kappa_iter.txt
#CO_CONF_FILE_KAPPA=${HOME}/intelCoConfig/kappa.txt

#CAF_SINGLE=1

# ========================= Vendor ============================ #

# ========================== Compiler ========================= #
# Compiler name here:
# For intel FC=ifort, for gnu FC=gfortran

FC=gfortran
MPIFC=mpif90

#FC=ifort

# ========================== Compiler ========================= #

# ====================== Libraries for GNU ==================== #
# If you wish to compile with gfortran provide the 
# path of open-coarray library, HDF5 library, BLAS 
# library and LAPACK library here

HDF5_INC=${HOME}/Applications/GNU/hdf5/include

COARR_LIB=${HOME}/Applications/GNU/opencoarrays/lib
HDF5_LIB=${HOME}/Applications/GNU/hdf5/lib
SPGLIB_LIB=${HOME}/Applications/GNU/spglib/lib

BLAS_LIB=${HOME}/Applications/GNU/blas
LAPACK_LIB=${HOME}/Applications/GNU/lapack

#OPENBLAS_LIB=${HOME}/Applications/GNU/OpenBLAS/lib

# ====================== Libraries for GNU ==================== #

# ==================== Libraries for Intel ==================== #
# If you wish to compile with ifort provide the 
# path of HDF5 library compiled with the intel 
# compilers here. Also uncomment the MKL_LIB to 
# use the intel-mkl library.

#HDF5_INC=${HOME}/Applications/Intel/hdf5/include
#
#HDF5_LIB=${HOME}/Applications/Intel/hdf5/lib
#SPGLIB_LIB=${HOME}/Applications/Intel/spglib/lib64
#MKL_LIB=${MKLROOT}/lib/intel64

# ==================== Libraries for Intel ==================== #

# ========================== Python3 ========================== #
#PY3_PATH=/usr/bin/python3
# ========================== Python3 ========================== #
#
