
SRC= kinds.f90 constants.f90 parse_cmd_line.f90 hdf5_wrap_mod.f90 IndxChng_mod.f90 unit_mod.f90 FC4_data_mod.f90 Helper_m.f90 DispMatFC4_mod.f90 main.f90 
OBJ=$(SRC:.f90=.o)

%.o: %.f90
	$(FC) $(FFLAGS) -o $@ $(INCFLAGS) -c $<

build: $(OBJ)
		$(MPIFC) $(FFLAGS) $(FFLINK) $(LDFLAGS) -o $(EXEC_NAME) $(OBJ) $(LIBS)

clean:
		rm -rf $(OBJ)
		rm -rf *.mod
		rm -rf $(EXEC_NAME)


