
SRC= kinds.f90 constants.f90 timer_class.f90 parse_cmd_line.f90 lapack_gfort.f90 IndxChng_mod.f90 unit_mod.f90 spglib_f08.f90 Symmetry_m.f90 CutInfo_m.f90 HelperRoutines.f90 FC_obj_m.f90 main.f90 
OBJ=$(SRC:.f90=.o)

%.o: %.f90
	$(FC) $(FFLAGS) -o $@ $(INCFLAGS) -c $<

build: $(OBJ)
		$(FC) $(FFLAGS) $(FFLINK) $(LDFLAGS) -o $(EXEC_NAME) $(OBJ) $(LIBS)

clean:
		rm -rf $(OBJ)
		rm -rf *.mod
		rm -rf $(EXEC_NAME)


